CREATE TABLE Actor (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    age int CHECK(age > 0) NOT NULL
);

CREATE TABLE Movie(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_production int CHECK(year_of_production > 1900) NOT NULL
);

CREATE TABLE Actor_Movie(
    actor_id int REFERENCES Actor(id),
    movie_id int REFERENCES Movie(id)
);